---

- name: Check if caffeine is already installed
  command: dpkg-query -W caffeine
  register: caffeine_check
  failed_when: caffeine_check.rc > 1
  changed_when: caffeine_check.rc == 1

- name: Add Caffeine repository
  apt_repository: repo="ppa:caffeine-developers/ppa"
  when: caffeine_check.rc == 1

- name: Install caffeine
  apt: pkg=caffeine update_cache=yes state=present
  when: caffeine_check.rc == 1
