---

- name: Check DragonDisk is already installed
  command: dpkg-query -W dragondisk
  register: dragondisk_check
  failed_when: dragondisk_check.rc > 1
  changed_when: dragondisk_check.rc == 1

- name: Download DragonDisk deb
  get_url:
    url="http://www.s3-client.com/download-amazon-s3-client/dragondisk_1.0.5-0ubuntu_amd64.deb"
    dest="/tmp/dragondisk_1.0.5-0ubuntu_amd64.deb"
  when: dragondisk_check.rc == 1

- name: Install DragonDisk
  apt: deb="/tmp/dragondisk_1.0.5-0ubuntu_amd64.deb"
  when: dragondisk_check.rc == 1
