---

- name: Check DragonDisk is already installed
  command: dpkg-query -W dragondisk
  register: dragondisk_check
  failed_when: dragondisk_check.rc > 1
  changed_when: dragondisk_check.rc == 1

- name: Download DragonDisk deb
  get_url:
    url="http://download.dragondisk.com/dragondisk_1.0.5-0ubuntu_amd64.deb"
    dest="/home/{{ local_user }}/Downloads/dragondisk_1.0.5-0ubuntu_amd64.deb"
  when: dragondisk_check.rc == 1

- name: Install DragonDisk
  apt: deb="/home/{{ local_user }}/Downloads/dragondisk_1.0.5-0ubuntu_amd64.deb"
  when: dragondisk_check.rc == 1
