---

- name: Install latex utils
  apt: pkg={{ items }} state=present
  vars:
    items:
      - texlive-latex-base
      - texlive
      - texlive-xetex
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-latex-extra
      - texlive-science
      - texlive-lang-spanish
      - texlive-bibtex-extra  # biblatex
      - pandoc
      - latexmk  # used by vim-tex
