---
- name: Install productivity packages
  become: yes
  apt: pkg={{ items }} state=present
  vars:
    items:
      - firefox
      - filezilla
      - thunderbird
      - mdp  # markdown presentations
      - ledger  # accouting for hackers
      - lm-sensors  # laptop sensor information (temp, fan rpm..)
      - beep
      - quassel  # IRC client based on weechat
      - ttf-mscorefonts-installer  # for fonts such as times new roman
      - csvkit
      - p7zip-full
      - flashplugin-installer  # flash
      - taskwarrior
      - telegram-desktop
      - zathura  # document reader
      - redshift
      - smartmontools
      - calibre

- name: Install design packages
  become: yes
  apt: pkg={{ items }} state=present
  vars:
    items:
      - imagemagick
      - pinta  # ~paint for linux
      - gimp

- import_tasks: spotify.yml
- import_tasks: games.yml
- import_tasks: slack.yml
- import_tasks: skype.yml
- import_tasks: discord.yml
- import_tasks: toggl.yml
- import_tasks: vlc_player.yml
- import_tasks: peek.yml
- import_tasks: latex.yml
- import_tasks: timewarrior.yml
