---
- name: Install productivity packages
  apt: pkg={{ item }} state=present
  with_items:
    - pass
    - firefox
    - filezilla
    - thunderbird
    - mdp
    - ledger
    - lm-sensors
    # LaTeX utils
    - texlive-latex-base
    - texlive
    - texlive-fonts-recommended
    - texlive-xetex
    - texlive-fonts-extra
    - texlive-latex-extra
    - texlive-science
    - pandoc
    # Scanner software
    - xsane
    # flash
    - flashplugin-installer

- name: Install CompizConfig tool for Unity 16.04
  apt: pkg=compizconfig-settings-manager state=present
  when: ansible_distribution_version == "16.04"

- import_tasks: spotify.yml
- import_tasks: slack.yml
- import_tasks: spideroak.yml
- import_tasks: toggl.yml
- import_tasks: skype.yml
- import_tasks: caffeine.yml
- import_tasks: albert.yml
- import_tasks: dragondisk.yml
- import_tasks: vlc_player.yml
