---
- name: Install productivity packages
  apt: pkg={{ item }} state=present
  with_items:
    - pass
    - firefox
    - filezilla
    - thunderbird
#     - protonmail-bridge

- import_tasks: spotify.yml
- import_tasks: slack.yml
- import_tasks: spideroak.yml
