---
- name: Install productivity packages
  apt: pkg={{ item }} state=present
  with_items:
    - pass
    - firefox
    - filezilla
    - thunderbird
    - mdp
#     - protonmail-bridge

- import_tasks: spotify.yml
- import_tasks: slack.yml
- import_tasks: spideroak.yml
- import_tasks: toggl.yml
- import_tasks: skype.yml
- import_tasks: caffeine.yml
- import_tasks: albert.yml
- import_tasks: dragondisk.yml
