---
- name: Check PDFtk is installed
  command: snap list pdftk
  register: pdftk_check
  failed_when: pdftk_check.rc > 1
  changed_when: pdftk_check.rc == 1

- name: Install PDFtk
  command: snap install pdftk
  when: pdftk_check is changed
