---
- name: Check if Qucs is already installed
  command: dpkg-query -W qucs
  register: qucs_check
  failed_when: qucs_check.rc > 1
  changed_when: qucs_check.rc == 1

- name: Add Qucs repository
  apt_repository: repo="ppa:fransschreuder1/qucs"
  when: qucs_check is changed

- name: Install Qucs
  apt: pkg=qucs update_cache=yes state=present
  when: qucs_check is changed

