---
- name: Check if spotify is already installed
  command: dpkg-query -W spotify-client
  register: spotify_check
  failed_when: spotify_check.rc > 1
  changed_when: spotify_check.rc == 1
#- name: Add Apt Keys
#  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id={{ item }} state=present
#  with_items:
#    - BBEBDCB318AD50EC6865090613B00F1FD2C19886
#    - 0DF731E45CE24F27EEEB1450EFDC8610341D9410

- name: Add repository
  apt_repository: repo='deb http://repository.spotify.com stable non-free'
  when: spotify_check.rc == 1

- name: Install spotify
  apt: name=spotify-client update_cache=yes state=present
  when: spotify_check.rc == 1
