---

- name: Check toggl is installed
  command: dpkg-query -W toggldesktop
  register: toggl_check
  failed_when: toggl_check.rc > 1
  changed_when: toggl_check.rc == 1

- name: Download toggl dependencies
  get_url:
    url="{{ item }}"
    dest="/tmp/"
  with_items:
    - "http://fr.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base0.10/libgstreamer-plugins-base0.10-0_0.10.36-1_amd64.deb"
    - "http://fr.archive.ubuntu.com/ubuntu/pool/universe/g/gstreamer0.10/libgstreamer0.10-0_0.10.36-1.5ubuntu1_amd64.deb"
  when: toggl_check is changed

- name: Install dependencies
  become: yes
  apt: deb="/tmp/{{ item }}"
  with_items:
    - "libgstreamer0.10-0_0.10.36-1.5ubuntu1_amd64.deb"
    - "libgstreamer-plugins-base0.10-0_0.10.36-1_amd64.deb"
  when: toggl_check is changed

- name: Install other APT dependencies
  become: yes
  apt: name={{ items }} state=present
  vars:
    items:
      - libqt5webengine5
      - libqt5webenginecore5
      - libqt5webenginewidgets5
      - libqt5quickwidgets5
  when: toggl_check is changed

- name: Download toggl deb
  get_url:
     url="https://toggl.com/api/v8/installer?app=td&platform=deb64&channel=stable"
     dest="/tmp/toggldesktop_amd64.deb"
  when: toggl_check is changed

- name: Install Toggle
  become: yes
  apt: deb="/tmp/toggldesktop_amd64.deb"
  when: toggl_check is changed
