- hosts: localhost
  vars_files:
      - vars/roles
  roles:
      - setup
      - { role: development, when: role_development == true }
      - { role: productivity, when: role_productivity == true }
      - { role: security, when: role_security == true }
      - { role: desktop, when: role_desktop == true }
