- name: Install i3WM and utilities
  become: yes
  apt: name={{ items }} state=present
  vars:
    items:
      - i3  # i3 wm
      - touchegg  # trackpad utils
      - xbacklight  # adjust screen light
      - feh  # change background image
      - arandr  # graphical tool to edit monitors interface
      - rofi  # alternative to dmenu
      - blueman  # tool to manage bluetooth from the status bar
      - pavucontrol  # tool to manage audio
      - lxappearance  # tool to configure GTK themes
      - maim  # tool to take screenshots
      - arc-theme  # Nice theme for GTK and QT
      - xautolock  # autolock after X mins
      - polybar # i3 bar similar to waybar
      - i3lock  # Lock screen

- name: Download playerctl package
  get_url:
    url="https://github.com/acrisci/playerctl/releases/download/v{{ bin_playerctl }}/playerctl-{{ bin_playerctl }}_amd64.deb"
    dest="/tmp/playerctl-{{ bin_playerctl }}_amd64.deb"
  when: "'playerctl' not in ansible_facts.packages"

- name: Install playerctl package
  become: yes
  apt: deb="/tmp/playerctl-{{ bin_playerctl }}_amd64.deb"
  when: "'playerctl' not in ansible_facts.packages"

- name: Check rofi-bluetooth is already installed
  stat:
    path: "{{ home }}/.local/bin/rofi-bluetooth"
  register: rofib_check
  changed_when: rofib_check.stat.exists == false

- name: Download rofi-bluetooth
  get_url:
    url: "https://raw.githubusercontent.com/ClydeDroid/rofi-bluetooth/master/rofi-bluetooth"
    dest: "{{ home }}/.local/bin/rofi-bluetooth"
    mode: "744"
  when: rofib_check is changed

- name: Check nmcli-rofi is already installed
  stat:
    path: "{{ home }}/.local/bin/nmcli-rofi"
  register: rofinm_check
  changed_when: rofinm_check.stat.exists == false

- name: Download nmcli-rofi
  get_url:
    url: "https://raw.githubusercontent.com/sineto/nmcli-rofi/master/nmcli-rofi"
    dest: "{{ home }}/.local/bin/nmcli-rofi"
    mode: "744"
  when: rofinm_check is changed
