---

- name: write keyboard configration
  template:
    src: keyboard.j2
    dest: /etc/default/keyboard
    force: yes
    owner: root
    group: root
    mode: 'u=rw,go=r'
  notify:
    - dpkg-reconfigure keyboard-configuration
