- name: Install SwayWM and utilities
  become: yes
  apt: pkg={{ items }} state=present
  vars:
    items:
      - sway
      - waybar                  # i3bar alternative
      - swayidle                # idle management
      - swaylock                # lock screen
      - wdisplays               # arandr alternative
      - pavucontrol             # tool to manage audio
      - pipewire                # tools needed for screensharing
      - brightnessctl           # lcd brightness config
      - grim                    # screenshot
      - slurp                   # screen selector (can be used with grim)
      - wl-clipboard            # clipboard tools
      - mako-notifier           # notification system for wayland
      - wofi                    # application launcher
      # - xdg-desktop-portal-wlr  # xdg-desktop-portal backend for wlroots

- name: Install nmcli-rofi
  get_url:
    url="https://raw.githubusercontent.com/sinetoami/nmcli-rofi/master/nmcli-rofi"
    dest="{{ home }}/.local/bin/nmcli-rofi"

- name: Add user to `video` group - needed for `brightnessctl`
  become: yes
  user:
    name: "{{ local_user }}"
    groups: "video"
    append: yes
