---
- name: Install security packages
  become: yes
  apt: name={{ items }} state=present
  vars:
    items:
      - clamav
      - rkhunter
      - exiftool
      - qpdf
      - nmap

- import_tasks: openvpn.yml
- import_tasks: preyproject.yml
- import_tasks: privacy.yml
- import_tasks: keepassxc.yml
- import_tasks: backup.yml
- import_tasks: pentesting.yml
- import_tasks: syncthing.yml
