---
- name: Install security packages
  apt: pkg={{ items }} state=present
  vars:
    items:
      - clamav
      - rkhunter

- import_tasks: openvpn.yml
- import_tasks: preyproject.yml
- import_tasks: privacy.yml
- import_tasks: keepassxc.yml
- import_tasks: backup.yml
- import_tasks: pentesting.yml
