---
- name: Install security packages
  apt: pkg={{ item }} state=present
  with_items:
    - clamav
    - rkhunter

- import_tasks: openvpn.yml
- import_tasks: preyproject.yml
- import_tasks: privacy.yml
- import_tasks: keepassxc.yml
- import_tasks: backup.yml
- import_tasks: pentesting.yml
