---

- name: Install OpenVPN and other tools
  become: yes
  apt: pkg={{ items }} state=present
  vars:
    items:
      - openvpn
      - network-manager-openvpn
      - network-manager-openvpn-gnome
  register: openvpn_installed

- name: Update openvpn configuration
  become: yes
  template:
    src: openvpn.j2
    dest: /etc/default/openvpn
    force: yes
    owner: root
    group: root
    mode: 'u=rw,go=r'
  when: openvpn_installed is changed

- name: Disable openvpn service
  become: yes
  systemd:
    name: openvpn
    enabled: no
  notify:
    - openvpn reload-systemd
  when: openvpn_installed is changed
