---

- name: Install OpenVPN
  apt: pkg=openvpn state=present

- name: Install OpenVPN binding for network manager
  apt: pkg={{ items }} state=present
  vars:
    items:
      - network-manager-openvpn
      - network-manager-openvpn-gnome
