---

- name: Download Prey deb
  get_url:
    url="https://downloads.preyproject.com/prey-client-releases/node-client/1.9.13/prey_1.9.13_amd64.deb"
    dest="/tmp/prey_1.9.13_amd64.deb"
  when: "'prey' not in ansible_facts.packages"

- name: Install Prey
  become: yes
  apt: deb="/tmp/prey_1.9.13_amd64.deb"
  when: "'prey' not in ansible_facts.packages"
