---

- name: Add Tor launcher repository
  become: yes
  apt_repository: repo="ppa:micahflee/ppa"

- name: Install Tor Browser Launcher & others
  become: yes
  apt: name={{ items }} state=present
  vars:
    items:
      - torbrowser-launcher
      - exiv2  # metadata editor
