---

- name: Add Syncthing repository key
  become: yes
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present

- name: Add Syncthing repository
  become: yes
  apt_repository: repo='deb https://apt.syncthing.net/ syncthing stable'

- name: Install Syncthing
  become: yes
  apt: name=syncthing state=present
