---

- name: (main) Install tmux & tools
  package: name={{ items }} state=present
  become: "{{ true if ansible_pkg_mgr != 'homebrew' else false }}"
  vars:
    items:
      - tmux
      - tmuxinator # will this work on linux?

- name: (main) Setup tmux variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- name: (main) Copy tmux config file
  template:
    src: tmux.conf.j2
    dest: "{{ home }}/.tmux.conf"
