- name: Check if blender is installed
  command: dpkg-query -W blender
  register: blender_check
  failed_when: blender_check.rc > 1
  changed_when: blender_check.rc == 1

- name: Add blender repository
  apt_repository: repo="ppa:thomas-schiex/blender"
  when: blender_check.rc == 1

- name: Install blender
  apt: pkg=blender update_cache=yes state=present
  when: blender_check.rc == 1
