---
- name: Install design packages
  apt: pkg={{ items }} state=present
  vars:
    items:
      - imagemagick
      - pinta  # ~paint for linux

- import_tasks: gimp.yml
- import_tasks: blender.yml
