---

- name: (main) Install development packages
  package: name={{ items }} state=present
  become: "{{ true if ansible_pkg_mgr != 'homebrew' else false }}"
  vars:
    items:
      - git
      - plantuml
      - tree
      - wget
      - jq
      - curl
      - fswatch
      - difftastic # macOS-only??

- name: (main) Copy .gitconfig
  copy:
    src: templates/gitconfig
    dest: "{{ home }}/.gitconfig"
