---

- name: Install OpenJDK
  apt: pkg=openjdk-8-jdk

- name: Check android is installed
  command: which /opt/android-sdk-linux/tools/android
  register: check_android
  failed_when: check_android.rc > 1
  changed_when: check_android.rc == 1

- name: Download Android tools
  get_url: url=http://dl.google.com/android/android-sdk_r24.3.4-linux.tgz dest=/tmp/android-sdk.tgz
  when: check_android is changed

- name: Unarchive Android download
  unarchive:
    src="/tmp/android-sdk.tgz"
    dest=/opt/
    copy=no
  become: yes
  when: check_android is changed

- name: Install Android SDKs
  shell: "echo \"y\" | /opt/android-sdk-linux/tools/android update sdk -u -a -t {{ items }}"
  vars:
    items:
      - tools
      - platform-tools
      - build-tools-23.0.1
      - build-tools-22.0.1
      - android-23
      - android-22
      - android-21
      - extra
  args:
    executable: /bin/bash
  when: check_android is changed

- name: Extra android tools
  apt: package={{ items }} state=present
  vars:
    items:
      - android-tools-adb
