---

# curl -s  | sudo apt-key add -
# echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
# sudo apt-get update
# sudo apt-get install -y kubectl

- name: Add kubectl's repository apt key
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add kubectl repository
  become: yes
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"

- name: Install kubectl & dependencies
  become: yes
  apt: pkg={{ items }} state=present
  vars:
    items:
      - apt-transport-https
      - gnupg2
      - curl
      - kubectl

- name: Check kind is installed
  command: which kind
  register: check_kind
  failed_when: check_kind.rc > 1
  changed_when: check_kind.rc == 1

- name: Download kind binary
  get_url:
    url="https://kind.sigs.k8s.io/dl/v0.9.0/kind-linux-amd64"
    dest="/usr/local/bin/kind"
    mode="0755"
  when: check_kind is changed
