---

- name: Install PostgreSQL client
  apt: pkg=postgresql-client-common state=present

- name: Install MySQL client
  apt: pkg={{ item }} state=present
  with_items:
    - mysql-client
    - libmysqlclient-dev

- name: Install MongoDB client
  apt: pkg=mongodb-clients state=present

- name: Install Redis client
  apt: pkg=redis-tools state=present
