---
- name: Install MySQL client
  apt: pkg={{ item }} state=present
  with_items:
    - mysql-client
    - libmysqlclient-dev

- name: Install Redis client
  apt: pkg=redis-tools state=present

- name: Install SQLite3
  apt: pkg=sqlite3 state=present

# Install MongoDB latest version
- name: Check MongoDB is installed
  command: dpkg-query -W mongodb-org*
  register: mongodb_check
  failed_when: mongodb_check.rc > 1
  changed_when: mongodb_check.rc == 1

- name: Import MongoDB org repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    state: present
  when: mongodb_check.rc == 1

- name: Add MongoDB ORG repo
  apt_repository: repo='deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse'
  when: mongodb_check.rc == 1

- name: Install MongoDB client
  apt: pkg=mongodb-org-shell update_cache=yes state=present
  when: mongodb_check.rc == 1

- name: Install MongoDB tools
  apt: pkg=mongodb-org-tools
  when: mongodb_check.rc == 1

# Install PostgreSQL latest version
- name: Check if PostgreSQL client is already installed
  command: dpkg-query -W postgresql-client-9.6
  register: psql_check
  failed_when: psql_check.rc > 1
  changed_when: psql_check.rc == 1

- name: Add PostgreSQL repo key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  when: psql_check.rc == 1

- name: Add PostgreSQL repo
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
  when: psql_check.rc == 1

- name: Install PostgreSQL client
  apt: pkg=postgresql-client-9.6 update_cache=yes state=present
  when: psql_check.rc == 1
