---

- name: Install MySQL client
  become: yes
  apt: pkg={{ items }} state=present
  vars:
    items:
      - mysql-client
      - libmysqlclient-dev

- name: Install Redis client
  become: yes
  apt: pkg=redis-tools state=present

- name: Install SQLite3
  become: yes
  apt: pkg={{ items }} state=present
  vars:
    items:
      - sqlite3
      - libsqlite3-dev

# -------
# MongoDB
# -------

- name: Import MongoDB org repo key
  become: yes
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present
  when: "'mongodb-clients' not in ansible_facts.packages"

- name: Add MongoDB ORG repo
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/4.4 multiverse'
  when: "'mongodb-clients' not in ansible_facts.packages"

- name: Install MongoDB client
  become: yes
  apt: pkg=mongodb-clients state=present
  when: "'mongodb-clients' not in ansible_facts.packages"

- name: Install MongoDB tools
  become: yes
  apt: pkg=mongo-tools
  when: "'mongodb-clients' not in ansible_facts.packages"


# ----------
# PostgreSQL
# ----------

- name: Add PostgreSQL repo key
  become: yes
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  when: "'postgresql-client-9.6' not in ansible_facts.packages"

- name: Add PostgreSQL repo
  become: yes
  apt_repository: repo="deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
  when: "'postgresql-client-9.6' not in ansible_facts.packages"

- name: Install PostgreSQL client
  become: yes
  apt: pkg=postgresql-client-9.6 state=present
  when: "'postgresql-client-9.6' not in ansible_facts.packages"
