---
- name: Install MySQL client
  apt: pkg={{ items }} state=present
  vars:
    items:
      - mysql-client
      - libmysqlclient-dev

- name: Install Redis client
  apt: pkg=redis-tools state=present

- name: Install SQLite3
  apt: pkg={{ items }} state=present
  vars:
    items:
      - sqlite3
      - libsqlite3-dev

# Install MongoDB latest version
- name: Check MongoDB is installed
  command: dpkg-query -W mongodb-clients
  register: mongodb_check
  failed_when: mongodb_check.rc > 1
  changed_when: mongodb_check.rc == 1

- name: Import MongoDB org repo key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present
  when: mongodb_check.rc == 1

- name: Add MongoDB ORG repo
  apt_repository:
    repo: 'deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/4.4 multiverse'
  when: mongodb_check.rc == 1

- name: Install MongoDB client
  apt: pkg=mongodb-clients state=present
  when: mongodb_check.rc == 1

- name: Install MongoDB tools
  apt: pkg=mongo-tools
  when: mongodb_check.rc == 1

# Install PostgreSQL latest version
- name: Check if PostgreSQL client is already installed
  command: dpkg-query -W postgresql-client-9.6
  register: psql_check
  failed_when: psql_check.rc > 1
  changed_when: psql_check.rc == 1

- name: Add PostgreSQL repo key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  when: psql_check.rc == 1

- name: Add PostgreSQL repo
  apt_repository: repo="deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
  when: psql_check.rc == 1

- name: Install PostgreSQL client
  apt: pkg=postgresql-client-9.6 update_cache=yes state=present
  when: psql_check.rc == 1
