---

- name: Add docker's apt key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  become: yes
  apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install docker & requirements
  become: yes
  apt: name={{ items }} state=present
  vars:
    items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce

- name: Add user to docker group
  user:
    name: "{{ local_user }}"
    groups: "docker"
    append: yes

- name: Get uname -s
  shell: uname -s
  register: uname_s
  changed_when: false

- name: Get uname -m
  shell: uname -m
  register: uname_m
  changed_when: false


# --------------
# Docker compose
# --------------
- name: Check docker-compose is installed
  command: which docker-compose
  register: check_dc
  failed_when: check_dc.rc > 1
  changed_when: check_dc.rc == 1

- name: Download docker-compose binary
  become: yes
  get_url:
    url="https://github.com/docker/compose/releases/download/{{ bin_docker_compose}}/docker-compose-{{ uname_s.stdout }}-{{ uname_m.stdout }}"
    dest="/usr/local/bin/docker-compose"
    mode="0755"
  when: check_dc is changed


# --------------
# Docker machine
# --------------

- name: Check docker-machine is installed
  command: which docker-machine
  register: check_dm
  failed_when: check_dm.rc > 1
  changed_when: check_dm.rc == 1

- name: Download docker-machine binary
  get_url:
    url="https://github.com/docker/machine/releases/download/{{ bin_docker_machine }}/docker-machine-{{ uname_s.stdout }}-{{ uname_m.stdout }}"
    dest="/tmp/docker-machine"
  when: check_dm is changed

- name: Install docker-machine
  command: install /tmp/docker-machine /usr/local/bin/docker-machine
  when: check_dm is changed
