---
- name: Configure vim using git repo
  git:
    repo: "{{ repo_dotfiles }}"
    dest: "/home/{{ local_user }}/.dotfiles/"
    version: master
  become: yes
  become_user: "{{ local_user }}"


- name: Create dotfiles symlinks
