---

- name: Install embedded utilities
  become: yes
  apt: pkg={{ items }} state=present
  vars:
    items:
      - minicom
      - picocom
      - arduino-core
      - arduino
      - arduino-mk
      - python-serial

- name: Install INO for arduino development
  pip: name=ino executable={{ home }}/.pyenv/shims/pipx
