---

- name: Check if FZF is already installed
  stat:
    path: "/home/{{ local_user }}/.fzf/"
  register: fzf_check

- name: Clone the FZF repo
  git:
    repo: "{{ repo_fzf }}"
    dest: "/home/{{ local_user }}/.fzf/"
    version: master
    depth: 1
  become: yes
  become_user: "{{ local_user }}"
  when: fzf_check.stat.exists == false


- name: Install FZF
  shell: "/home/{{ local_user }}/.fzf/install"
  become: yes
  become_user: "{{ local_user }}"
  when: fzf_check.stat.exists == false
