---
- name: Install requirements
  apt: pkg={{ items }} state=present
  vars:
    items:
      - dconf-cli

- name: Check gruvbox is already configured
  stat:
    path: "/home/{{ local_user }}/.gnome-terminal-colors"
  register: shell_check
  changed_when: shell_check.stat.exists == false

- name: Download the gnome-terminal-colors-solarized repo
  git:
    repo: "{{ repo_gnome_terminal_solarized }}"
    dest: "/home/{{ local_user }}/.gnome-terminal-colors/"
    version: master
  when: shell_check is changed
  become: yes
  become_user: "{{ local_user }}"

- name: Configure the gnome-terminal
  shell: "dbus-launch /home/{{ local_user }}/.gnome-terminal-colors/install.sh -s gruvbox-dark -p {{ local_terminal_profile }}"
  become: yes
  become_user: "{{ local_user }}"
  when: shell_check is changed


- name: Install inconsolata font
  apt: pkg=fonts-inconsolata state=present
