---

- name: Install development packages
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - htop
    - tmux
    - ctags
    - figlet
    - tree
    - silversearcher-ag
    - youtube-dl
    - wget
    - plantuml
    - grep
    - fonts-powerline


#- keybase


# Import other tasks

- import_tasks: fzf.yml
- import_tasks: vim.yml
- import_tasks: fd.yml
- import_tasks: flamegraph.yml
- import_tasks: dotfiles.yml
- import_tasks: gnome_terminal.yml
- import_tasks: python.yml
