---

- name: Install nvm dependencies
  become: yes
  apt: pkg={{ items }} state=present
  vars:
    items:
      - build-essential
      - libssl-dev

- name: Check if nvm is already installed
  stat:
    path: "{{ home }}/.nvm/"
  register: nvm_check

- name: Download nvm installation script
  get_url:
     url="https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh"
     dest="/tmp/nvm_install.sh"
  when: nvm_check.stat.exists == false

- name: Install nvm
  command: "bash /tmp/nvm_install.sh"
  when: nvm_check.stat.exists == false
