---

- name: Use pyls with vim
  pip: name=python-language-server executable=pip3

- name: Instal virtualenv
  pip: name=virtualenv executable=pip3

- name: Add Pyflame repository
  apt_repository: repo="ppa:trevorjay/pyflame"

- name: Install Pyflame
  apt: pkg=pyflame update_cache=yes state=present
