---

- name: Use pyls with vim
  pip: name=python-language-server executable=pip3

- name: Instal virtualenv
  pip: name=virtualenv executable=pip3

- name: Add Pyflame repository
  apt_repository: repo="ppa:trevorjay/pyflame"

- name: Install Pyflame
  apt: pkg=pyflame update_cache=yes state=present

- name: Add Python3.6 repository on 16.04
  apt_repository: repo="ppa:deadsnakes/ppa"
  when: ansible_distribution_version == "16.04"

- name: Install Python3.6 on 16.04
  apt: pkg=python3.6 update_cache=yes state=present
  when: ansible_distribution_version == "16.04"
