---

- name: Install python tools
  apt: name={{ items }} state=present
  vars:
    items:
      - python-pysqlite2

- name: Check pyenv exists
  stat:
    path: "/home/{{ local_user }}/.pyenv"
  register: pyenv_check
  changed_when: pyenv_check.stat.exists == false

- name: Install pyenv requirements to build Python versions
  apt: name={{ items }} state=present
  vars:
    items:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
      - python-openssl
  when: pyenv_check is changed

- name: Install pyenv as python version manager
  git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "/home/{{ local_user }}/.pyenv"
    version: master
  become: yes
  become_user: "{{ local_user }}"
  when: pyenv_check is changed

- name: Install python3 versions using pyenv
  shell: /home/{{ local_user }}/.pyenv/bin/pyenv install {{ item }}
  with_items: "{{ bin_python }}"
  become: yes
  become_user: "{{ local_user }}"
  when: pyenv_check is changed

- name: Set new installed python versions as global
  command: /home/{{ local_user }}/.pyenv/bin/pyenv global {{ bin_python | join(" ") }}
  become: yes
  become_user: "{{ local_user }}"
  when: pyenv_check is changed

- name: Install pipx
  pip: executable=/home/{{ local_user }}/.pyenv/shims/pip3 name=pipx

- name: Check PYLS is already installed
  stat:
    path: "/home/{{ local_user }}/.local/bin/pyls"
  register: pyls_check
  changed_when: pyls_check.stat.exists == false

- name: Install PYLS
  pip: name=python-language-server executable=/home/{{ local_user }}/.pyenv/shims/pipx
  become: yes
  become_user: "{{ local_user }}"
  when: pyls_check is changed

- name: Install PYLS dependencies
  command: /home/{{ local_user }}/.pyenv/shims/pipx inject python-language-server {{ item }}
  with_items:
    - python-language-server[rope]
    - python-language-server[pyflakes]
    - python-language-server[mccabe]
    - python-language-server[pycodestyle]
    - pyls-mypy
  become: yes
  become_user: "{{ local_user }}"
  when: pyls_check is changed

- name: Check pipenv exists
  stat:
    path: "/home/{{ local_user }}/.local/share/virtualenvs"
  register: pipenv_check
  changed_when: pipenv_check.stat.exists == false

- name: Download pipenv installer
  get_url:
    url="https://raw.githubusercontent.com/kennethreitz/pipenv/master/get-pipenv.py"
    dest="/tmp/get-pipenv.py"
  when: pipenv_check is changed

- name: Install pipenv
  command: python /tmp/get-pipenv.py
  when: pipenv_check is changed

- name: Check Pyflame is installed
  command: dpkg-query -W pyflame
  register: pyflame_check
  failed_when: pyflame_check.rc > 1
  changed_when: pyflame_check.rc == 1

- name: Add Pyflame repository
  apt_repository: repo="ppa:trevorjay/pyflame"
  when: pyflame_check.rc == 1

- name: Install Pyflame
  apt: pkg=pyflame update_cache=yes state=present
  when: pyflame_check.rc == 1

- name: Install Python2.x header file
  apt: pkg=python-dev state=present

- name: Install tkinter
  apt: pkg={{ items }} state=present
  vars:
    items:
      - python-tk

- name: Check py-spy is installed
  stat:
    path: /home/{{ local_user }}/.cargo/bin/py-spy
  register: check_pyspy
  changed_when: check_pyspy.stat.exists == false

- name: Install py-spy
  pip: name=py-spy executable=/home/{{ local_user }}/.pyenv/shims/pipx
  become: yes
  become_user: "{{ local_user }}"
  when: check_pyspy is changed
