---
- name: Check R is already installed
  command: dpkg-query -W r-base
  register: rlang_check
  failed_when: rlang_check.rc > 1
  changed_when: rlang_check.rc == 1

- name: Add R repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E084DAB9
    state: present
  when: rlang_check is changed

- name: Add R repository
  apt_repository: repo="deb https://cloud.r-project.org/bin/linux/ubuntu {{ ansible_distribution_release }}-cran35/"
  when: rlang_check is changed

- name: Install R
  apt: pkg={{ items }} update_cache=yes state=present
  when: rlang_check is changed
  vars:
    items:
      - r-base
      - r-base-dev
