---
- name: Check R is already installed
  command: dpkg-query -W R
  register: rlang_check
  failed_when: rlang_check.rc > 1
  changed_when: rlang_check.rc == 1

- name: Add R repository
  apt_repository: repo="ppa:marutter/rrutter"
  when: rlang_check is changed

- name: Install R
  apt: pkg={{ items }} update_cache=yes state=present
  when: rlang_check is changed
  vars:
    items:
      - r-base
      - r-base-dev
