---

- name: Add vim repository
  become: yes
  apt_repository: repo="ppa:jonathonf/vim"

- name: Install vim
  become: yes
  apt: pkg=vim state=present

- name: Check vimrc is configured
  stat:
    path: "{{ home }}/.vim"
  register: vimrc_check
  changed_when: vimrc_check.stat.exists == false

- name: Configure vim using git repo
  git:
    repo: "{{ repo_vimrc }}"
    dest: "{{ home }}/.vim/"
    version: master
  when: vimrc_check is changed

- name: Create symlink to use the configuration
  file:
    src: "{{ home }}/.vim/vimrc"
    dest: "{{ home }}/.vimrc"
    state: link
  when: vimrc_check is changed
