---

- name: Install compass
  gem: name=compass state=present

- name: Install less
  apt: pkg=node-less state=present

- name: Check if ChromeDriver is installed
  stat: path=/usr/bin/chromedriver
  register: check_chromedriver
  changed_when: check_chromedriver.stat.exists == false

- name: Download ChromeDriver
  get_url:
     url="https://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip"
     dest=/tmp/
  when: check_chromedriver is changed

- name: Unzip ChromeDriver
  unarchive:
    src=/tmp/chromedriver_linux64.zip
    dest=/tmp/
    copy=no
  when: check_chromedriver is changed

- name: Install ChromeDriver
  copy:
    src: /tmp/chromedriver
    dest: /usr/bin/chromedriver
    owner: root
    group: root
    mode: 0755
  when: check_chromedriver is changed
