---

- name: Install Alacritty
  become: yes
  apt: name=alacritty state=present
  register: alacritty_install

- name: Use Alacritty as the default terminal
  become: yes
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/alacritty
  when: alacritty_install is changed

- name: Run fc-cache
  become: yes
  command: "fc-cache -f"
  when: alacritty_install is changed
